[package]
name = "rust-raytracer-in-a-weekend"
version = "0.1.0"
authors = ["brian"]

[dependencies]
assert_approx_eq = "1.0.0"
num              = "0.1.37"
num-traits       = "0.1.37"
rand             = "0.3"
